// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMetric = `-- name: CreateMetric :exec
INSERT INTO metric (id, type, delta, value, hash)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) ON CONFLICT (id) DO UPDATE SET delta = EXCLUDED.delta, value=EXCLUDED.value
`

type CreateMetricParams struct {
	ID    string
	Type  string
	Delta pgtype.Int8
	Value pgtype.Float8
	Hash  pgtype.Text
}

func (q *Queries) CreateMetric(ctx context.Context, arg CreateMetricParams) error {
	_, err := q.db.Exec(ctx, createMetric,
		arg.ID,
		arg.Type,
		arg.Delta,
		arg.Value,
		arg.Hash,
	)
	return err
}

const getMetricByID = `-- name: GetMetricByID :one
SELECT id, type, delta, value, hash FROM metric WHERE id = $1
`

func (q *Queries) GetMetricByID(ctx context.Context, id string) (Metric, error) {
	row := q.db.QueryRow(ctx, getMetricByID, id)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Delta,
		&i.Value,
		&i.Hash,
	)
	return i, err
}

const getMetrics = `-- name: GetMetrics :many
SELECT id, type, delta, value, hash FROM metric
`

func (q *Queries) GetMetrics(ctx context.Context) ([]Metric, error) {
	rows, err := q.db.Query(ctx, getMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metric
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Delta,
			&i.Value,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
