// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Metric struct {
	ID    string
	Type  string
	Delta pgtype.Int8
	Value pgtype.Float8
	Hash  pgtype.Text
}
